### ISSUE TITLE
Reduce boiler-plate code for AddProblem

### ISSUE THREAD

**Issue by nickmeinhold** [crowdleague/crowdleague#183]

**Comment by T-Davis** [comment]
- [ ] Implement an extension function on StreamController to add a Problem using a Map of Types of BaseProblem sub-classes.
A starting template can be found in [the_process](https://github.com/crowdleague/the_process/blob/dev/lib/extensions/stream_extensions.dart)

- [ ] Clean up verbose AddProblem code where possible
