### ISSUE TITLE
OtherAuthOptionsPage overflows on tap input feilds

### ISSUE THREAD

**Issue by tamari-gray** [crowdleague/crowdleague#205]
page overflows when tap on input text feilds

# Suggestion:
have keyboard overlay content, not push up bottom section of page

**Comment by nickmeinhold** [comment]
I think the chat app had an interesting solution - I think it's somewhere in: [chat_app/chat_page.dart at test · Adventures-In/chat_app](https://github.com/Adventures-In/chat_app/blob/test/lib/widgets/messages/chat_page.dart)

I'll see if I can find exactly what I'm referring to and report back...

**Comment by nickmeinhold** [comment]
I think it was [resizeToAvoidBottomInset](https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html): 

> if there is an onscreen keyboard displayed above the scaffold, the body can be resized to avoid overlapping the keyboard, which prevents widgets inside the body from being obscured by the keyboard.

Although apparently it defaults to true so maybe I'm getting this all wrong - do we just have a completely different use-case?  In the chat app we wanted to make we still saw the bottom of the [widget inside the scaffold body] as that was where text was being entered.  

I think your solution was very close to perfect for our use case, the only thing I think we might consider adding are 
- (as you suggested) adding scrolling so widget behind the keyboard can be moved 
- automatically scrolling to the best position (eg. with the text field that has focus is just above the keyboard 

Anyway, fwiw I reckon the best way forward is to use the solution you already have and we both have a play on some different screen sizes and see what we think.  

Sorry for the wild goose chase! 🦆 🦢 🐦
