### ISSUE TITLE
preserve text fields when navigate from sign in screen to sign up

### ISSUE THREAD

**Issue by tamari-gray** [crowdleague/crowdleague#262]
#### Problem
On navigate between sign in/sign up screens, the text fields are being reset. This means the user will have to retype anything from the previous screen and could result in the loss of some golden UX points.

#### Solution
remove reseting text fields (on navigate between sign in/up)

- [ ] CreateAccountLink (onTap)
    - [ ] redux state
    - [ ] local form state
- [ ] SignInLink(onTap)
    - [ ] redux state
    - [ ] local form state

**Comment by nickmeinhold** [comment]
Thanks for creating the issue! 

![Alt Text](https://memegenerator.net/img/instances/73502160/gold-point.jpg)
