### ISSUE TITLE
rename "signing in with firebase.." loading text

### ISSUE THREAD

**Issue by tamari-gray** [crowdleague/crowdleague#264]
#### Is your feature request related to a problem? Please describe.
After signing in with an auth provider, we see "signing in with firebase..." + loading widget.
This is really helpfull as a developer to see what step in the sign in process we are on, but as a user, the word firebase would confuse me.

#### Describe the solution you'd like
I would like to rename "signing in with firebase.." to "signing into crowdleague".

**Comment by nickmeinhold** [comment]
Sounds good to me mate!  Totally agree with your reasoning re: 'firebase' being confusing to a user
